### ISSUE TITLE
PDF Constancia de Inscripción

### ISSUE THREAD

**Issue by marcoschicote** [eeng/afipws#18]
Hola! Venimos usando esta librería y funciona joya. Gracias!

Quería consultarles si hay forma de generar el PDF de la constancia de inscripción en AFIP de un CUIT.

Gracias!
Marcos

**Comment by eeng** [comment]
Hola @marcoschicote, me alegro que les sirva.
Hay algunos WS para consultar los datos de la constancia pero, que yo sepa, no hay ninguno que permita generar el PDF.
Saludos.

**Comment by marcoschicote** [comment]
> Hola @marcoschicote, me alegro que les sirva.
> Hay algunos WS para consultar los datos de la constancia pero, que yo sepa, no hay ninguno que permita generar el PDF.
> Saludos.

Gracias por la respuesta! Se te ocurre alguna alternativa si necesito generar el PDF?

**Comment by eeng** [comment]
Y está complicado por el captcha... Si no lo tuviera se podría usar algo como Mechanize para automatizar el proceso de entrar a la página de la AFIP y generar la constancia, pero el captcha te obliga a requerir intervención del usuario...

Tendrías que consultarles a ellos a ver si ofrecen alguna alternativa. Quizás te dicen que podés usar el WS de constancia para obtener los datos del contribuyente y luego generar vos un PDF similar que tenga la misma validez. 
Te dejo el mail de contacto que usamos en algún momento: sri@afip.gob.ar

**Comment by marcoschicote** [comment]
> Y está complicado por el captcha... Si no lo tuviera se podría usar algo como Mechanize para automatizar el proceso de entrar a la página de la AFIP y generar la constancia, pero el captcha te obliga a requerir intervención del usuario...
> 
> Tendrías que consultarles a ellos a ver si ofrecen alguna alternativa. Quizás te dicen que podés usar el WS de constancia para obtener los datos del contribuyente y luego generar vos un PDF similar que tenga la misma validez.
> Te dejo el mail de contacto que usamos en algún momento: [sri@afip.gob.ar](mailto:sri@afip.gob.ar)

gracias!!
