### ISSUE TITLE
Cache en disco y recuperacion del Ticket de Acceso

### ISSUE THREAD

**Issue by codingwaysarg** [eeng/afipws#3]
Hola, quería saber si había forma (si es que no lo hace ya), de cachear y recuperar el Ticket de Acceso desde disco, para evitar el problema de "El CEE ya posee un TA valido para el acceso al WSN solicitado" en caso de reinicio del servicio.

Gracias.

**Comment by codingwaysarg** [comment]
Solucionado en el PR #4

**Comment by eeng** [comment]
Resuelto en #4
