### ISSUE TITLE
Padron A5

### ISSUE THREAD

**Issue by marcoschicote** [eeng/afipws#6]
Hola
Estoy tratando de obtener información sobre distintos CUITs consultando el servicio de la AFIP. Sin embargo, no puedo dar de alta el padron A4 y leo que es para entes gubernamentales ([ver acá](https://groups.google.com/d/msg/pyafipws/wTb_1SMwhqg/o6G6f0ERAgAJ)). Habrá cambiado algo? Alguien sabe si hay compatibilidad de la gema con el padron A5?

Gracias!

**Comment by eeng** [comment]
Hola @marcoschicote.
El padron A5 no está implementado pero nosotros usamos el servicio ws_sr_constancia_inscripcion  (implementado en la clase WSConstanciaInscripcion) para esa tarea, sin problemas. Me parece haber leído en algún lado que son el mismo servicio (de hecho ahora veo en la doc que ambos usan el mismo WSDL) y que la AFIP había renombrado el A5 al ws_sr_constancia_inscripcion, así que te recomiendo usar este último.

**Comment by marcoschicote** [comment]
Gracias @eeng. Al padron A4 siguen teniendo acceso? Lo que leo es que es para entes gubernamentales, aunque en la documentación del servicio no dice nada.

**Comment by eeng** [comment]
De nada. El A4 se incorporó en el PR #5 a pedido de su autor, pero nosotros nunca lo usamos así que no sabría decirte si es para gubernamentales o no.
